name: CI/CD Pipeline

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:    
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

  docker:
    needs: sonarqube    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' &&  needs.sonarqube.result == 'success' 
    name: Publish Docker Image
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit    

  deploy:
    needs: docker    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' &&  needs.docker.result == 'success' 
    name: Deploy to GKE
    uses: ./.github/workflows/infra-google.yml
    secrets: inherit
    
