name: Main

on:  
  workflow_dispatch:
  pull_request:
   types: [opened, synchronize, reopened]    
   branches:
     - main

jobs:
  sonarqube:    
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

  docker:
    needs: sonarqube    
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
